"""
Two-Stage 'Screen & Simulate' Optimization Engine
Chains Mixed-Integer Linear Programming (Stage 1: Multi-Objective MILP)
into Stochastic Monte Carlo Simulation (Stage 2: Full Distribution Tournament).
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple, Set
import numpy as np
import pandas as pd

from analytics.optimizer import FPLOptimizer
from analytics.montecarlo import MonteCarloEngine


@dataclass(frozen=True)
class ParetoCandidateSquad:
    """Stage 1 Output: Candidate squad generated by MILP under a specific objective."""
    objective_name: str
    generator_type: str = "MILP"
    squad_names: List[str] = field(default_factory=list)
    transfers_in: List[str] = field(default_factory=list)
    transfers_out: List[str] = field(default_factory=list)
    total_cost: float = 0.0
    bank_remaining: float = 0.0
    projected_score: float = 0.0


@dataclass
class StochasticSquadEvaluation:
    """Stage 2 Output: Monte Carlo stress-test distribution metrics."""
    candidate: ParetoCandidateSquad
    mean_points: float
    floor_p10: float
    median_p50: float
    ceiling_p90: float
    standard_deviation: float
    net_gain_vs_current: float
    win_probability_pct: float
    zero_minute_rate_pct: float = 0.0
    sharpe_ratio: float = 0.0


@dataclass
class TwoStageOptimizationReport:
    """Final decision report comparing all Pareto candidate squads."""
    baseline_squad: List[str]
    baseline_mean: float
    baseline_p10: float
    baseline_p90: float
    evaluated_candidates: List[StochasticSquadEvaluation]
    winner_balanced: Optional[StochasticSquadEvaluation]
    winner_safe_floor: Optional[StochasticSquadEvaluation]
    winner_explosive_ceiling: Optional[StochasticSquadEvaluation]


class MILPCandidateGenerator:
    """
    Stage 1: Dedicated Pareto Candidate Generator using Scipy MILP.
    Executes multi-objective knapsack sweeps and deduplicates identical squad permutations.
    """
    DEFAULT_OBJECTIVES: List[Tuple[str, str]] = [
        ("balanced", "fdr_moneyball"),
        ("high_attack", "xgi"),
        ("setpiece_focus", "setpiece_moneyball"),
        ("momentum", "form")
    ]

    def __init__(self, optimizer: FPLOptimizer):
        self.optimizer = optimizer

    def generate_candidates(
        self,
        current_squad: List[str],
        bank: float = 3.7,
        num_transfers: int = 1,
        objectives: Optional[List[Tuple[str, str]]] = None
    ) -> List[ParetoCandidateSquad]:
        """
        Runs MILP sweeps across multiple distinct objective weight vectors.
        Deduplicates identical 15-man squad compositions automatically.
        """
        sweeps = objectives or self.DEFAULT_OBJECTIVES
        candidates: List[ParetoCandidateSquad] = []
        seen_squads: Set[frozenset] = set()

        for label, obj_name in sweeps:
            result = self.optimizer.optimize_transfers(
                current_player_names=current_squad,
                bank_balance=bank,
                max_transfers=num_transfers,
                objective=obj_name
            )
            if not result.get("success"):
                continue

            squad_df = result.get("squad")
            if squad_df is not None and "web_name" in squad_df.columns:
                squad_names = squad_df["web_name"].tolist()
            else:
                squad_names = result.get("new_squad", [])

            squad_key = frozenset(squad_names)
            if squad_key in seen_squads:
                continue
            seen_squads.add(squad_key)

            # Format transfer names cleanly
            tin_raw = result.get("transfers_in", [])
            tout_raw = result.get("transfers_out", [])

            if isinstance(tin_raw, pd.DataFrame):
                tin = tin_raw["web_name"].tolist() if "web_name" in tin_raw.columns else []
            elif isinstance(tin_raw, list):
                tin = [p["web_name"] if isinstance(p, dict) else str(p) for p in tin_raw]
            else:
                tin = []

            if isinstance(tout_raw, pd.DataFrame):
                tout = tout_raw["web_name"].tolist() if "web_name" in tout_raw.columns else []
            elif isinstance(tout_raw, list):
                tout = [p["web_name"] if isinstance(p, dict) else str(p) for p in tout_raw]
            else:
                tout = []

            candidates.append(ParetoCandidateSquad(
                objective_name=label,
                generator_type="MILP",
                squad_names=squad_names,
                transfers_in=tin,
                transfers_out=tout,
                total_cost=float(result.get("total_cost", 0.0)),
                bank_remaining=float(result.get("bank_remaining", 0.0)),
                projected_score=float(result.get("objective_score", 0.0))
            ))

        return candidates


class TwoStageOptimizer:
    """
    Orchestration Engine bridging MILP candidate generation with Monte Carlo evaluation.
    """
    def __init__(self, optimizer: FPLOptimizer, mc_engine: MonteCarloEngine):
        self.optimizer = optimizer
        self.mc_engine = mc_engine
        self.generator = MILPCandidateGenerator(optimizer)

    def run_screen_and_simulate(
        self,
        current_squad: List[str],
        bank: float = 3.7,
        num_transfers: int = 1,
        n_sims: int = 1000,
        risk_profile: str = "balanced",
        objectives: Optional[List[Tuple[str, str]]] = None
    ) -> TwoStageOptimizationReport:
        """
        Executes the two-stage pipeline:
        1. Evaluates baseline squad under N Monte Carlo simulations.
        2. Generates Pareto-diverse transfer candidates via Stage 1 MILP sweeps.
        3. Stress-tests all candidate squads in Stage 2 Monte Carlo simulations.
        4. Ranks candidate squads by utility and returns a structured report.
        """
        # 1. Baseline squad Monte Carlo simulation
        base_eval = self.mc_engine.optimize_lineup_and_substitutions(
            squad_names=current_squad,
            n_sims=n_sims
        )
        base_summary = base_eval["squad_summary"]
        base_mean = float(base_summary["mean_total"])
        base_p10 = float(base_summary["floor_p10"])
        base_p90 = float(base_summary["ceiling_p90"])
        base_raw = base_summary.get("simulation_totals")
        if base_raw is not None:
            base_totals = np.asarray(base_raw, dtype=float)
        else:
            base_totals = np.random.normal(base_mean, base_summary.get("std", 10.0), size=n_sims)

        # 2. Stage 1: Generate Pareto candidates via MILP sweeps
        candidates = self.generator.generate_candidates(
            current_squad=current_squad,
            bank=bank,
            num_transfers=num_transfers,
            objectives=objectives
        )

        # 3. Stage 2: Monte Carlo evaluation of candidates
        evaluated: List[StochasticSquadEvaluation] = []
        for cand in candidates:
            cand_eval = self.mc_engine.optimize_lineup_and_substitutions(
                squad_names=cand.squad_names,
                n_sims=n_sims
            )
            cand_summary = cand_eval["squad_summary"]
            c_mean = float(cand_summary["mean_total"])
            c_p10 = float(cand_summary["floor_p10"])
            c_p50 = float(cand_summary["median_p50"])
            c_p90 = float(cand_summary["ceiling_p90"])
            c_std = float(cand_summary["std"])
            c_raw = cand_summary.get("simulation_totals")
            if c_raw is not None:
                c_totals = np.asarray(c_raw, dtype=float)
            else:
                c_totals = np.random.normal(c_mean, c_std, size=n_sims)

            diff = c_totals - base_totals
            net_gain = round(float(np.mean(diff)), 2)
            win_prob = round(float(np.mean(diff > 0) * 100), 1)
            sharpe = round(float(net_gain / (c_std + 1e-6)), 3)

            evaluated.append(StochasticSquadEvaluation(
                candidate=cand,
                mean_points=c_mean,
                floor_p10=c_p10,
                median_p50=c_p50,
                ceiling_p90=c_p90,
                standard_deviation=c_std,
                net_gain_vs_current=net_gain,
                win_probability_pct=win_prob,
                sharpe_ratio=sharpe
            ))

        # 4. Determine winners across risk dimensions
        if evaluated:
            winner_balanced = max(evaluated, key=lambda x: x.net_gain_vs_current)
            winner_safe_floor = max(evaluated, key=lambda x: x.floor_p10)
            winner_explosive_ceiling = max(evaluated, key=lambda x: x.ceiling_p90)
        else:
            winner_balanced = None
            winner_safe_floor = None
            winner_explosive_ceiling = None

        return TwoStageOptimizationReport(
            baseline_squad=current_squad,
            baseline_mean=base_mean,
            baseline_p10=base_p10,
            baseline_p90=base_p90,
            evaluated_candidates=evaluated,
            winner_balanced=winner_balanced,
            winner_safe_floor=winner_safe_floor,
            winner_explosive_ceiling=winner_explosive_ceiling
        )
