"""
automation/cpn/tokens.py
Kurt Jensen Coloured Petri Net Tokens (Color Sets Sigma).
Strictly immutable frozen dataclasses per Python engineering standards.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any
import pandas as pd


class K3Status(str, Enum):
    """Kleene 3-Valued Logic Values."""
    TRUE = "TRUE"
    FALSE = "FALSE"
    UNKNOWN = "UNKNOWN"


@dataclass(frozen=True)
class Color_Deadline:
    """Timing token referenced monotonically to API deadline."""
    gameweek: int
    deadline_utc: datetime
    cutoff_disambiguation_utc: datetime
    n_sims: int = 5000


@dataclass(frozen=True)
class Color_Session:
    """Pre-authenticated session credentials and health metrics."""
    auth_cookie: str
    csrf_token: str
    expires_at: datetime
    is_authenticated: bool
    last_keepalive_utc: datetime


@dataclass(frozen=True)
class Color_MarketData:
    """Ingested market telemetry and player data."""
    elements: pd.DataFrame
    fixtures: list[dict[str, Any]]
    odds: dict[str, Any]
    injury_flags: dict[int, dict[str, Any]]


@dataclass(frozen=True)
class Color_SquadState:
    """Verified manager squad marking including ghost squad tracking for Free Hit."""
    entry_id: int
    squad_ids: list[int]
    bank: float
    free_transfers: int
    chips_available: dict[str, bool]
    active_chip: str | None
    selling_prices: dict[int, float]
    ghost_squad_ids: list[int]
    ghost_bank: float
    ghost_selling_prices: dict[int, float]


@dataclass(frozen=True)
class Color_OptimizedPlan:
    """Candidate lineup and transfer portfolio generated by optimizer."""
    plan_id: str
    starters: list[int]
    bench: list[int]
    captain: int
    vice_captain: int
    transfers: list[dict[str, Any]]
    chip: str | None
    expected_utility: float
    formation_tuple: tuple[int, int, int]
    fallback_plan: dict[str, Any] | None = None
    is_degraded: bool = False
    chip_degraded_reason: str | None = None
    contingency_tree: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Color_GuardToken:
    """Decomposed guard condition token scattered for resolution."""
    plan_id: str
    guard_name: str
    status: K3Status
    subject_id: int | None
    doubt_type: str
    is_fatal: bool
    context: dict[str, Any]
    resolved_at: datetime | None = None


@dataclass(frozen=True)
class Color_Receipt:
    """Cryptographically verified terminal execution receipt."""
    http_status: int
    timestamp: datetime
    payload_hash: str
    confirmation_id: str


@dataclass(frozen=True)
class Color_Alert:
    """Operator diagnostic alert deposited in Dead-Letter Queue."""
    severity: str
    reason: str
    context: dict[str, Any]
    timestamp: datetime
