"""
automation/challenge_cpn/tokens.py
Kurt Jensen Coloured Petri Net Tokens for FPL Challenge Mode.
Immutable frozen dataclasses per Python engineering standards.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Any, Optional
import pandas as pd

from analytics.challenge.contracts import ChallengeRuleSet, ChallengeOptimalSquad, EvaluatedChallengeCandidate
from analytics.challenge.picker import ChallengePickerResult
from analytics.challenge.model_validator import ModelValidationReport


class SagaStatus(str, Enum):
    """Saga transaction execution states."""
    INITIATED = "INITIATED"
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    RETRY_PENDING = "RETRY_PENDING"
    COMPENSATED = "COMPENSATED"
    FAILED = "FAILED"


@dataclass(frozen=True)
class Color_ChallengeRule:
    """Dynamic rule token representing active gameweek format."""
    gameweek: int
    name: str
    rule_set: ChallengeRuleSet
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengeMarket:
    """Market telemetry token containing player pool, odds, and fixtures."""
    elements_df: pd.DataFrame
    fixtures: List[Dict[str, Any]]
    gameweek: int
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengeSquadState:
    """Current live lineup marking retrieved from FPL Challenge."""
    entry_id: int
    picks: List[Dict[str, Any]]
    captain_id: int
    vice_captain_id: int
    element_ids: List[int]
    is_live: bool = False
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengePlan:
    """Candidate lineup and transfer plan generated by ChallengePicker."""
    picker_result: ChallengePickerResult
    archetype: str
    gameweek: int
    expected_utility: float
    tournament_p99: float
    plan_id: str
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengeValidation:
    """Model error and configuration comparison token."""
    plan_id: str
    report: ModelValidationReport
    is_valid: bool
    error_count: int
    warning_count: int
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengeSagaToken:
    """State-tracking token for the Saga submission and verification loop."""
    transaction_id: str
    plan_id: str
    entry_id: int
    attempt: int
    max_retries: int
    status: SagaStatus
    payload: Dict[str, Any]
    expected_element_ids: List[int]
    expected_captain_id: int
    expected_vice_captain_id: int
    last_response: Optional[Dict[str, Any]] = None
    verification_diff: Optional[Dict[str, Any]] = None
    error_message: Optional[str] = None
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class Color_ChallengeReceipt:
    """Cryptographically verifiable receipt of confirmed Challenge submission."""
    transaction_id: str
    entry_id: int
    gameweek: int
    element_ids: List[int]
    captain_id: int
    vice_captain_id: int
    http_status: int
    attempts_required: int
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    verified: bool = True


@dataclass(frozen=True)
class Color_ChallengeAlert:
    """Operational alert raised during Challenge CPN execution."""
    level: str                                  # "INFO", "WARNING", "CRITICAL"
    source_transition: str
    message: str
    context: Dict[str, Any] = field(default_factory=dict)
    timestamp_utc: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
